### PR TITLE
Added 2015 Meeting Minutes from Jan 19th to Mar 6th

### PR DESCRIPTION
**Pull request by JasonWangYVR**

### CODE REVIEW

**Comment by fosskers** [comment]
Can't merge, it seems.

**Comment by jleung51** [comment]
@trevorg16 | @CtrlShiftGo: Both documents contain the exact same text content and layouts; however, the existing PDF is formatted as an A4 size document while the PDF in the merge request is formatted as a Letter size document.

It's safe to accept either version.

**Comment by fosskers** [comment]
Then this can be closed.

**Comment by jleung51** [comment]
@fosskers: My apologies, I was unclear! I was talking only about the one conflicting document between `master` and this merge request.

There are still 4 new documents in this merge request which don't yet exist in the repository, so I'd recommend reopening and merging them!

**Comment by fosskers** [comment]
My bad, I didn't notice.

**Pull request merged**
